### ISSUE TITLE
v2ex过来的

### ISSUE THREAD

**Issue by coderzhw** [xuya227939/LiuJiang-Blog#115]
你这个用issuse做的博客用什么加速的？这种除了静态资源不是还得调GitHub 的api获取issue的内容吗？

**Comment by xuya227939** [comment]
@coderzhw 既然来了，先点赞一波。

**Comment by coderzhw** [comment]
如何点赞？问题回答一波呗？

**Comment by xuya227939** [comment]
star一下。。。b

静水流深 ***@***.***> 于2021年4月8日周四 上午8:49写道：

**Comment by coderzhw** [comment]
star完了，加速是怎么加速的呢？还是没回答我的问题，老哥，issuse写博客貌似得调用https://api.github.com/graphql这个接口获取数据的吧？

**Comment by xuya227939** [comment]
@coderzhw 
1、调用的GitHub API，在源码中就有，翻翻看就找到了
2、https://app.netlify.com，使用该网站提供的免费加速
